name: Update Streak Stats
on:
  schedule:
    - cron: '0 0 * * *'   # প্রতিদিন UTC 00:
  workflow_dispatch:        # চাইলে manually Run করতে পারবে

jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: be-next/github-streak-stats-action@v1
        with:
          username: taniashahida-dev
          token: ${{ secrets.GITHUB_TOKEN }}
          output-path: profile/streak.svg
          timezone: Asia/Dhaka
          theme: default
          hide-border: true

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
